- name: Build Artifact Root.war & SQL file to be copied in the files/ directory
  import_playbook: build.yml

- name: Set Hosts to Ip mapping in /etc/hosts file of all servers
  import_playbook: set_host_ip_map.yml

- name: Setup dbserver
  import_playbook: db.yml

- name: Deploy SQL file on Dbserver
  import_playbook: dbdeploy.yml

- name: Setup Memcache service
  import_playbook: memcache.yml


- name: Setup rabbitmq service
  import_playbook: rabbitmq.yml


- name: Setup Tomcat application server
  import_playbook: appserver.yml

- name: Setup Nginx webserver
  import_playbook: web.yml

